service: stellar-pay-svc
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  logs:
    httpApi: true
    environment:
      LOG_LEVEL: info

functions:
  exchangeRates:
    handler: src/http/conversion/exchangeRates/lambda.handler
    events:
      - http:
          path: conversion/exchange-rates
          method: get
  timeSeries:
    handler: src/http/conversion/timeSeries/lambda.handler
    events:
      - http:
          path: conversion/timeseries
          method: get
  convertCurrency:
    handler: src/http/conversion/convertCurrency/lambda.handler
    events:
      - http:
          path: conversion/convert
          method: get

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 3000